[정병연] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #12
Opened 2021-12-21 02:11 UTC by daydream-03

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 회원가입 기능 구현
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 정규식을 이용한 이메일, 휴대폰, 비밀번호 유효성 검사
- 이메일, 비밀번호 필수 요구사항 설정
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 별도의 validator 함수를 만들어 진행하는 방향을 채택했지만, 데코레이터를 사용하는 방법도 있지 않을까라는 고민이 계속 남아있습니다. 데코레이터로도 회원가입 기능 구현이 가능한지 알고 싶습니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 05:00 UTC, Kang-kyunghun requested changes

2021-12-21 05:00 UTC, Kang-kyunghun commented on students/byeongyeon/westagram/users/views.py
> +from users.validator        import validate_email, validate_password, validate_mobile
사용하지 않는 모듈은 제거해 주세요.
```suggestion
import json

from django.http     import JsonResponse
from django.views    import View

from users.models    import User
from users.validator import validate_email, validate_password, validate_mobile
```

2021-12-21 05:00 UTC, Kang-kyunghun commented on students/byeongyeon/westagram/users/views.py
> +                )
1. if 조건을 만족하게 되면 함수가 종료 되기 때문에 if 아래 로직이 실행 되지 않습니다. 따라서 elif 대신에 if만 가지고도 충분히 구현이 가능하고, 가독성 면에서도 더 좋습니다.

```suggestion
    def post(self, request):
        data = json.loads(request.body)
        
        try:
            if User.objects.filter(email=data['email']).exists():
                return JsonResponse({"message": "Email is already in use"}, status=400)
            
            if not validate_email(data["email"]):
                return JsonResponse({"message": "Email format is invalid"}, status=400)
            
            if not validate_password(data["password"]):
                return JsonResponse({"message": "Password format is invalid"}, status=400)
            
            if not validate_mobile(data["mobile"]):
                return JsonResponse({"message": "Mobile number format is invalid"}, status=400)
                     
            User.objects.create(
                name     = data['name'],
                email    = data['email'],
                password = data['password'],
                mobile   = data['mobile'],
                address  = data['address'],
                age      = data['age']
            )
```

2021-12-21 05:00 UTC, Kang-kyunghun commented on students/byeongyeon/westagram/users/views.py
> +        return JsonResponse({"message":"SUCCESS"}, status=201)
1. except를 retrun 아래로 내려주세요. except는 더 추가 될 수 있고, 로직 흐름상 최종 결과는 try 안에 있는 것이 좋습니다.
2. return message는 front에서 보는 메시지 입니다. 장문의 메시지 보다는 명확한 메시지로 보내 주어야 front에서도 해당 메시지를 parsing해서 로직을 구현하기 편해집니다.
```suggestion
            return JsonResponse({"message":"SUCCESS"}, status=201)
        except KeyError:
            return JsonResponse({"message": "KEY_ERROR"}, status=400)
```

2021-12-21 05:11 UTC, daydream-03 commented on students/byeongyeon/westagram/users/views.py
> +        return JsonResponse({"message":"SUCCESS"}, status=201)
리뷰 반영하여 수정하였습니다.

2021-12-21 07:27 UTC, kyeongraekim requested changes
사소한 수정 사항 다시 한 번 확인해주세요!~

2021-12-21 07:27 UTC, kyeongraekim commented on students/byeongyeon/westagram/users/models.py
>      password   = models.CharField(max_length=256)             #암호화를 대비한 max_length 설정
불필요한 주석을 삭제해주세요!~

2021-12-21 07:27 UTC, kyeongraekim commented on students/byeongyeon/westagram/users/urls.py
> +    path('/register', RegisterView.as_view()),                          #/users/register로 httpie 명령어 날릴 것
이곳에서도 불필요한 주석들이 보이네요. 깃허브에 올라오는 소스코드들은 최종 완성본의 퀄리티를 지녀야함을 잊지 말아주세요!~ 일반 행정문서 작업 후 결재를 올릴 때 심혈을 기울이듯이 깃허브도 동일한 자세로 자신이 푸시하기 직전의 내용을 git diff, git status 의 명령어를 써가며 비교한 후 올려주셔야 합니다~

2021-12-21 07:35 UTC, daydream-03 commented on students/byeongyeon/westagram/users/urls.py
> +    path('/register', RegisterView.as_view()),                          #/users/register로 httpie 명령어 날릴 것
수정하였습니다!

2021-12-21 07:37 UTC, daydream-03 commented on students/byeongyeon/westagram/users/urls.py
> +    path('/register', RegisterView.as_view()),                          #/users/register로 httpie 명령어 날릴 것
사전에 작업 중이던 로그인 기능이 포함되어 들어갔습니다.
해당 내용 삭제 후 다시 제출합니다.

2021-12-21 07:59 UTC, kyeongraekim requested changes
마이너한 수정사항이 마지막으로 보여서 리뷰 남깁니다!~

2021-12-21 07:59 UTC, kyeongraekim commented on students/byeongyeon/westagram/users/views.py
> +                return JsonResponse({"message": "Email format is invalid"}, status=400)
email = data["email"]
password = data["password"]

등 중복되어 나올 매핑이 위 처럼 변수처리되어 있었다면 불필요한 연산을 여러번 반복하지 않았을 것 같네요!~

2021-12-21 08:06 UTC, daydream-03 commented on students/byeongyeon/westagram/users/views.py
> +                return JsonResponse({"message": "Email format is invalid"}, status=400)
변수 선언으로 불필요한 매핑의 반복을 제거하였습니다.

2021-12-21 12:08 UTC, Kang-kyunghun requested changes

2021-12-21 12:08 UTC, Kang-kyunghun commented on students/byeongyeon/westagram/users/views.py
> +                return JsonResponse({"message": "Mobile number format is invalid"}, status=400)
```suggestion
            if User.objects.filter(email=email).exists():
                return JsonResponse({"message": "Email is already in use"}, status=400)
            
            if not validate_email(email):
                return JsonResponse({"message": "Email format is invalid"}, status=400)
            
            if not validate_password(password):
                return JsonResponse({"message": "Password format is invalid"}, status=400)
            
            if not validate_mobile(mobile):
                return JsonResponse({"message": "Mobile number format is invalid"}, status=400)
```

2021-12-21 12:08 UTC, Kang-kyunghun commented on students/byeongyeon/westagram/users/views.py
> +            )
위에서 선언한 변수를 활용하면 더 좋을 것 같습니다.
```suggestion
            User.objects.create(
                email    = email,
                password = password,
                mobile   = mobile,
                name     = data['name'],
                address  = data['address'],
                age      = data['age']
            )
```

2021-12-21 12:22 UTC, daydream-03 commented on students/byeongyeon/westagram/users/views.py
> +            )
수정사항 반영하였습니다!

2021-12-22 01:42 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-22 01:42 UTC, merged