[이민석] Mission 4: 로그인 기능 구현
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #14
Opened 2021-12-21 05:08 UTC by leeminseok8

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 05:58 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2021-12-21 05:58 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +            user = User.objects.get(
email하나만 들어가는 거니, 복수의 정보가 들어가는게 아니라면 get(email=email) 로 처리하는게 가독성이 더 좋아질 것 같네요!~

2021-12-21 05:58 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +        except:
except만 사용해서 Error를 핸들링 하는 경우는 피해야 합니다. 그 이유는 파이썬에 발생시키는 모든 에러에 대해서 except문으로 빠지게 됩니다. 이런 구조로 코드를 작성한다면 당연히 디버깅 하기가 어려워 지겠죠?

(디버깅 : 나중에 기능에 버그가 생겼을 경우에 어디서 문제가 생겼는지 찾기가 어려움)

```python
try:
    ..
except:
    ..
```

결론적으로 `try, except`문을 사용해서 error를 핸들링하는 경우 아래와 같이 에러를 명확하게 잡아주셔야 합니다.

```python
try:

except KeyError:
    return ..    
```

2021-12-21 05:58 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +                raise Exception('The password is wrong')
이곳도 아래의 내용처럼 Exception 전체의 거대한 에러를 잡아오는 것 보다 JsonResponse로 Invalid Password 정도의 메세지로 올바르지 않은 비밀번호였다는 것을 힌트로 제공하는 기능을 하면 좋을 것같네요.

2021-12-21 07:03 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2021-12-21 07:03 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +from django.db              import DatabaseError
불필요한 임포트문은 삭제해주세요!~

2021-12-21 07:03 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +                raise User.DoesNotExist()
이곳에서 if-raise 를 따로 해주실 필요 없으십니다. 위 57번라인에서 해당되는 이메일이 없다면 아래 except 문에 걸려서 저절로 User.DoesNotExist 에러를 내게될 거에요!~

2021-12-21 07:11 UTC, leeminseok8 commented on students/minseok/westagram/users/views.py
> +                raise User.DoesNotExist()
섬세한 리뷰 항상 감사드려요 경래님~~!!

2021-12-21 07:12 UTC, leeminseok8 commented
User.DoesNotExist() 부분 오류검증까지 마치고 다시 push했습니다!

2021-12-21 07:56 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2021-12-21 07:56 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +            User.DoesNotExist()
기능상 무의미한 코드가 58번 라인에 동떨어져있어 보이네요! 확인 부탁드립니다.

2021-12-22 01:51 UTC, Kang-kyunghun requested changes

2021-12-22 01:51 UTC, Kang-kyunghun commented on students/minseok/westagram/users/views.py
> +            validation_password(password)
input과 DB 내용을 비교하는 로직이므로 validation이 필요하지는 않을 것 같습니다.

2021-12-22 04:55 UTC, leeminseok8 commented on students/minseok/westagram/users/views.py
> +            validation_password(password)
회원가입에서 이미 정규식을 통과한 데이터이기 때문에 정규식을 다시 거치지 않아도 된다는 의미인거죠? 감사합니다 바로 수정하겠습니다!

2021-12-22 08:50 UTC, kyeongraekim approved these changes
LGTM!~

2021-12-22 09:24 UTC, merged