[이정석] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #15
Opened 2021-12-21 06:25 UTC by sxxk2

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-21 07:00 UTC, kyeongraekim requested changes
아래 내용 확인 후 수정해주세요!~

2021-12-21 07:00 UTC, kyeongraekim commented on students/jeongseoklee/westagram/users/models.py
> +    user_id    = models.CharField(max_length=50, unique=True)
user_id 아까 구두로 설명해드린 것처럼 삭제해주세요!~

2021-12-21 07:00 UTC, kyeongraekim commented on students/jeongseoklee/westagram/users/views.py
> +# ‘^[a-zA-Z0-9+-_.]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+$’
불필요한 내용 주석으로 남겨져있네요 푸시전에는 자신이 짜놓은 코드를 꼭 꼼꼼이 확인해주시는 것을 습관화해주세요!~

2021-12-21 07:00 UTC, kyeongraekim commented on students/jeongseoklee/westagram/users/views.py
> +password_validator = re.compile('^(?=.*[a-zA-Z])(?=.*[!@#$%^*+=-])(?=.*[0-9]).{8,}$')
정규표현식을 쓰실거면 complie이 아닌 re.match를 사용해주셔야 더 효율적인 코드 진행이 이루어집니다.

2021-12-21 07:00 UTC, kyeongraekim commented on students/jeongseoklee/westagram/users/views.py
> +            #패스워드에 8자리이상, 문자, 숫자, 특수문자의 조합이 아니라면 에러
불필요한 한글 주석 삭제해주세요!~

2021-12-21 07:00 UTC, kyeongraekim commented on students/jeongseoklee/westagram/users/views.py
> +
라인 스페이싱 공백이 2칸일 필요는 없어 보이네요. 한 칸으로 줄여주세요.

2021-12-21 07:00 UTC, kyeongraekim commented on students/jeongseoklee/westagram/users/views.py
> +            if User.object.filter(email=email).exist():
email이 선언되어있지 않아서 돌아가지 않는 코드처럼 보여집니다.

2021-12-21 08:44 UTC, sxxk2 commented
위 사항들과 정규식패턴비교코드 수정 후 푸시 하였습니다.

2021-12-21 12:05 UTC, Kang-kyunghun requested changes

2021-12-21 12:05 UTC, Kang-kyunghun commented on students/jeongseoklee/westagram/users/views.py
> +            )
= 기준으로 정렬해 주세요.

해당 컨벤션은 다른 곳에서는 하지 않는 컨밴션일 수는 있지만, 현재 소속된 곳의 컨벤션을 지키는 것은 생각보다 중요합니다. 
```suggestion
            User.objects.create(
                email    = email,
                password = password,
                mobile   = data['mobile'],
                username = data['username'],
            )
```

2021-12-21 12:20 UTC, sxxk2 commented on students/jeongseoklee/westagram/users/views.py
> +            )
컨벤션 적용 후 다시 푸시 완료하였습니다.

2021-12-22 01:43 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-22 01:43 UTC, merged