[이찬주] Mission 6: 로그인 JWT 적용
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #17
Opened 2021-12-21 10:47 UTC by evnif11

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 JWT 토큰 발행
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 로그인 성공시 토큰 발행
- 로그인 검증하는 데코레이터 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-22 04:33 UTC, Kang-kyunghun requested changes

2021-12-22 04:33 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/decorators.py
> +from users.models import User
```suggestion
from my_settings  import SECRET_KEY, ALGORITHM
from users.models import User
```

2021-12-22 04:33 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/decorators.py
> +from django.contrib.auth.models import User
import을 기준으로 정렬해 주세요.(wecode 컨벤션)
`from django.contrib.auth.models import User`을 import 한 이유가 있을까요? 사용하지 않으면 제거해 주세요. 
```suggestion
import jwt
from jwt.exceptions             import DecodeError, ExpiredSignatureError
from django.http                import JsonResponse
from django.contrib.auth.models import User
```

2021-12-22 04:33 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/decorators.py
> +            if User.objects.filter(id=payload['user_id']).exists() and payload['exp'] < datetime.now():
payload에 'exp' 조건을 넣어 주면 따로 datetime으로 비교 안 하고 jwt.decode에서 바로 판단을 해주는 걸로 알고 있습니다.
exp time 짧게 줘서 한 번 테스하면 좋을 것 같아요.

2021-12-22 04:33 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/decorators.py
> +                return JsonResponse({'message':'SUCCESS'}, status=200)
데코레이터를 만들었는데, 데코레이터로서 작용을 할려면 return을 어떻게 해야 할지 조금 더 조사해 봤으면 좋겠어요.

2021-12-22 04:33 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
>                  raise ValidationError('INVALID_PASSWORD')
email이든 비밀번호든 잘 못 되었을 때 에러 메시지를 통일하는 것이 좋습니다. 
email이 잘 못 되었는지, 비밀번호가 잘 못 되었는지 몰라야 보안상 더 좋습니다. 
```suggestion
            if not bcrypt.checkpw(password.encode('utf-8'), user.password.encode('utf-8')):
                raise ValidationError('INVALID_USER')
```

2021-12-22 04:46 UTC, evnif11 commented on students/chanjoo/westargram/users/views.py
>                  raise ValidationError('INVALID_PASSWORD')
보안상 이유이군요 새롭게 알게 되었네요 감사합니다.

2021-12-22 09:00 UTC, evnif11 commented
유저가 존재하지 않는 에러를 DOES NOT EXISTS 에러로 사용할 수 있나요? 아님 지금처럼 validation error로 처리하는게 맞나요

2021-12-23 02:47 UTC, Kang-kyunghun requested changes

2021-12-23 02:47 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
> +            access_token = jwt.encode(data, SECRET_KEY, ALGORITHM)
= 기준으로 정렬해 주세요.
```suggestion
            data         = {'user_id': user.id, 'exp':datetime.now() + timedelta(days=1)}
            access_token = jwt.encode(data, SECRET_KEY, ALGORITHM)
```

2021-12-23 02:50 UTC, Kang-kyunghun commented
> 피드백 사항 전부 반영했습니다.
> 
> 질문사항 : 유저가 존재하지 않는 에러를 DOES NOT EXISTS 에러로 사용할 수 있나요? 아님 지금처럼 validation error로 처리하는게 맞나요

Validation error는 많은 것을 포괄하고 있습니다. 그래서 당연히 DOES NOT EXISTS가 조금 더 의미가 맞고, 해당 기능에서는 따로 Auth와 관련된 Error로 만드는 것이 더 정확합니다.
프론트에게 전달되는 메시지는 저희 정해주고 있는 것이 날아가기 때문에 상관은 없지만, 서버 입장에서 로그를 남길 때 조금 더 error을 명확하게 하면 좋습니다.

2021-12-23 05:44 UTC, Kang-kyunghun requested changes

2021-12-23 05:44 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
> +                raise ValidationError('INVALID_USER')
bcrypt로 hash된 정보를 확인 하는 방법 다시 한 번 확인해 보고 적용해 주세요.
미션 4에서는 비밀번호가 hash되어 있지 않았기 때문에 동시에 확인 가능 했지만, 지금은 그것이 불가능 합니다.
따라서 로직 순서가
1. email 확인
2. 확인된 email로 user 정보 get
3. get user의 password와 input password 비교 이런 순서로 가야 합니다.

2021-12-23 07:14 UTC, evnif11 commented
고쳤습니다!

2021-12-23 07:22 UTC, Kang-kyunghun requested changes

2021-12-23 07:22 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
> +            if not User.objects.filter(email=email, password=password.encode('utf-8')).exists():
```suggestion
            if not User.objects.filter(email=email).exists():
```

2021-12-23 07:32 UTC, evnif11 commented
<img width="1056" alt="스크린샷 2021-12-23 오후 4 32 31" src="https://user-images.githubusercontent.com/50139787/147204899-d0e6c862-5a9b-4009-b4e5-4712fcb07322.png">


200 OK

2021-12-23 07:41 UTC, kyeongraekim requested changes
요청하신 수정 리뷰사항 식별하여서 아래와 같이 남겨드렸습니다 참고해주세요!~

2021-12-23 07:41 UTC, kyeongraekim commented on students/chanjoo/westargram/users/decorators.py
> +    return wrapper
```python

def login_required(func):
    def wrapper(self, request, *args, **kwargs):
        try:
            access_token = request.headers.get('Authorization', None)
            payload      = jwt.decode(access_token, SECRET_KEY, algorithms=ALGORITHM)
            user         = User.objects.get(id=payload['id'])
            request.user = user

        return func(self, request, *args, **kwargs)

        except User.DoesNotExist:
            return JsonResponse({'MESSAGE' : 'INVALID_USER'}, status=400)

2021-12-23 07:41 UTC, kyeongraekim commented on students/chanjoo/westargram/users/decorators.py
> +    return wrapper
- request.user를 변수명으로 지어주셔야 추후에 다른 view class에서 활용가능하실 거에요!~

- 지금으로선 필요없을 수 있어 보이지만 해당 코드 기능의 확장 가능성을 고려하여 args와 kwargs도 추가해주세요~

- 참고사항으로 if절이 아닌 try-except 구문으로 짜보면 위과 같이 짜볼 수 있을 것 같네요!~

2021-12-23 07:41 UTC, kyeongraekim commented on students/chanjoo/westargram/users/views.py
> +            data         = {'user_id': user.id, 'exp':datetime.now() + timedelta(days=1)}
'user_id' : user.id 보다는 어떠한 id 값인지 알아보기 힘들게 단순한 'id' : user.id 로 수정하는 것은 어떨까요?

2021-12-23 08:47 UTC, Kang-kyunghun commented
LGTM~!!!

2021-12-23 08:48 UTC, merged