[이찬주] Mission 2: 모델링
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #5
Opened 2021-12-16 11:44 UTC by evnif11

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- user 모델링
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- user 어플리케이션 추가
- user 모델링
- 모델 마이그레이션

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 field를 사용하는게 나을까요?
- 비밀번호 필드는 단방향 암호화로 해시값으로 저장될테니 길이를 넉넉하게 줬는데, 어느정도로 주는게 좋을까요?
- 코딩 컨벤션에 대해서 찾아봤는데 PEP8 <Whitespace in Expressions and Statements> 에서 equal 줄을 맞춰주는걸 잘못된 예시로 소개하고 있습니다. 구글 코딩가이드에서는 탭과 스페이스도 혼용하지 말라는 규칙이 있는데 과연 equals 를 맞춰주는게 더 효율적인지 의문이 듭니다. 변수명이 길어지면 나머지 변수도 모두 수정해주어야하고, 혹여라도 깃헙에서 불필요한 conflict가 발생할 수 있는 위험이 있어서 저는 조심스럽게 안쓰는게 어떨지 의견을 드려봅니다. (커뮤니케이션의 일환이라고 생각해요!)

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-16 15:33 UTC, kyeongraekim requested changes
아래 간단한 수정 가능 내용 확인 후 반영해보세요!~

2021-12-16 15:33 UTC, kyeongraekim commented on students/chanjoo/westargram/users/models.py
> +    phone_number = models.CharField(max_length=30)
- 인스타 그램 서비스 기획에 처럼 최종 가입후 작성 될 수 도 있는 추가 기입 정보도 기획에 반영해보는 것이 어떨까요?
- 위 사항이 반영된다면 null 값도 허용되어야 할 것 같은데 장고에서는 어떻게 반영해볼 수 있을까요?

2021-12-16 15:33 UTC, kyeongraekim commented on students/chanjoo/westargram/users/models.py
> +    phone_number = models.CharField(max_length=30)
그리고 다음부터 라벨링 꼭 붙혀주세요!~

2021-12-17 01:07 UTC, evnif11 commented
## 수정 사항 간략한 한줄 요약
- 피드백 요청 반영해 user 모델 수정

## 수정 사항들 자세한 내용
- 실제 인스타그램 가입절차를 반영해 추가적으로 username을 필수적으로 받을 수 있게 했습니다
- 이외에 date_of_birth, website, gender, introduction, profile_photo 등의 부가 정보 필드를 추가했습니다

## 기타 질문 및 특이 사항
- 전화번호 혹은 이메일 두개중 하나를 필수로 입력하도록 하는 설정은 validation 파트에서 할 수 있도록 하고 두 필드 모두 Null = True 옵션을 주었는데 맞을까요?
- 장고는 기본 설정이 null=false인데 반해 대부분 DB 기본 설정이 null=true 인걸로 알고 있습니다(mysql 포함). 장고에서만 다르게 의도한 이유가 따로 있을까요?   
- 기존 모델을 수정하면서 데이터가 없음에도 불구하고 select 옵션을 주었기에, non-nullable 필드인 'username'에 부득이하게 default 값을 주었습니다.
<img width="983" alt="스크린샷 2021-12-17 오전 10 07 25" src="https://user-images.githubusercontent.com/50139787/146471942-d18542dc-1157-4a91-8646-14dc97e5eaab.png">

2021-12-17 02:27 UTC, kyeongraekim requested changes
아래 고민해볼 만한 내용 한 번 추가해드렸습니다!~ 확인 후 반영해보세요~

2021-12-17 02:27 UTC, kyeongraekim commented on students/chanjoo/westargram/users/models.py
> +    phone_number  = models.CharField(max_length=30, unique=True, default='')
그리고 Phone_number가 주된 로그인 방법이라면 default 값이 빈 문자열이 필요가 없어 보일 것 같네요!~

그리고 위와 조금은 다른 이야기지만 통상적으로 unique=True와 default='' 또는 blank=True는 모델 속성값으로 동시적용을 안하는 편입니다.  한 번 그 이유를 곰곰히 생각해보세요!~

2021-12-17 02:36 UTC, kyeongraekim commented on students/chanjoo/westargram/users/models.py
> +    phone_number  = models.CharField(max_length=30, unique=True, default='')
- 전화번호 혹은 이메일 두개중 하나를 필수로 입력하도록 하는 설정은 validation 파트에서 할 수 있도록 하고 두 필드 모두 Null = True 옵션을 주었는데 맞을까요?
=> 구두로 설명드린 내용입니다.

- 장고는 기본 설정이 null=false인데 반해 대부분 DB 기본 설정이 null=true 인걸로 알고 있습니다(mysql 포함). 장고에서만 다르게 의도한 이유가 따로 있을까요?
=> null=False 가 기본인 db들은 데이터의 무결성(integrity)를 보다 엄격하게 관리하는데 주안점을 둔다고 보시면 됩니다. 여타 웹프레림워크 보다 더 거대한 프로젝트를 다루는데 유리한 장고는 특히 자체적으로 form validation과 DRF의 serialization validation 기능을 보유하고 있고 유효한 데이터인지 여부를 중요하게 생각하는 프레임워크라서 그렇다고 볼 수 있습니다!~

2021-12-17 03:58 UTC, kyeongraekim approved these changes
LGTM!~

2021-12-17 03:58 UTC, merged