Project Models
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #6
Opened 2021-12-17 02:51 UTC by daydream-03

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- Westagram Models 작업 완료
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- models.py 작업 완료
- 이메일 field는 unique=True로 중복되는 주소가 없도록 설정

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 주소 정도의 길이의 텍스트는 CharField와 TextField 중 어느 것이 적합한지 궁금합니다.

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [x] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [x] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [x] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [x] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-17 07:12 UTC, Kang-kyunghun requested changes

2021-12-17 07:12 UTC, Kang-kyunghun commented on students/byeongyeon/westagram/users/models.py
> +    address  = models.CharField(max_length=500)             #질문사항 : 주소 정도의 텍스트 정보는 TextField 사용이 적합한지?
1. 비밀번호는 암호화를 대비하여 256정도로 길이를 늘려주세요.
2. Charfield가 약 2000~3000정도의 길이를 커버 할 수 있습니다. 이 이상이 넘어가면 Text Field를 사용하시면 됩니다.
3. 데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-17 07:56 UTC, daydream-03 commented on students/byeongyeon/westagram/users/models.py
> +    address  = models.CharField(max_length=500)             #질문사항 : 주소 정도의 텍스트 정보는 TextField 사용이 적합한지?
수정사항 반영하였습니다. 
리뷰 부탁드립니다.

2021-12-18 01:51 UTC, Kang-kyunghun commented
LGTM~!!

2021-12-18 01:51 UTC, merged