[이찬주] Mission 3: 회원가입 기능 구현
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #7
Opened 2021-12-17 06:14 UTC by evnif11

## 수정 사항 간략한 한줄 요약
- 회원가입 엔드포인트 구현
		 
## 수정 사항들 자세한 내용
- 핸드폰 번호로 회원가입 할 수 있음
- 정규표현식 활용해서 이메일, 핸드폰 번호, 패스워드 validation 로직 구현
- 회원가입 성공할 시 201 상태 코드 반환

## 기타 질문 및 특이 사항

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-18 02:09 UTC, Kang-kyunghun requested changes

2021-12-18 02:09 UTC, Kang-kyunghun commented on students/chanjoo/westargram/westargram/urls.py
> +    path('user', include('users.urls')),
```suggestion
    path('users', include('users.urls')),
```
복수를 더 많이 사용합니다.

2021-12-18 02:09 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
> +                raise ValidationError('이미 가입된 핸드폰 번호입니다.')
```suggestion
                raise ValidationError('invalid phon_number')
```
메시지는 영어로 간결하게 해주세요. 저희가 한국인하고만 협업하는 것이 아닙니다. 따라서 공통어인 영어를 사용해 주세요. 그리고 이 메시지는 사용자가 아닌 프론트엔드가 보는 메시지이기 때문에 자세하게 설명하지 않으셔도 됩니다.(메시지는 예시일 뿐이니 적절한 메시지를 넣어주시면 됩니다.)

2021-12-18 02:09 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
> +            return JsonResponse({'message': 'KEY_ERROR'}, status = 400)
```suggestion
        except KeyError:
            return JsonResponse({'message': 'KEY_ERROR'}, status = 400)
```
메시지를 사용하고 있지 않으므로 제거해 주세요.

2021-12-18 02:09 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
> +
email 중복 확인은 따로 안 하나요?

2021-12-18 02:09 UTC, Kang-kyunghun commented on students/chanjoo/westargram/users/views.py
> +from re import M
view 본문에서는 사용하고 있는 것 같으니 제거해 주세요.

2021-12-18 03:04 UTC, evnif11 commented on students/chanjoo/westargram/users/views.py
> +                raise ValidationError('이미 가입된 핸드폰 번호입니다.')
오.. 딱 궁금했던 부분인데 명쾌하게 설명해주셔서 감사합니다 ! 수정하겠습니다

2021-12-18 03:14 UTC, evnif11 commented on students/chanjoo/westargram/users/views.py
> +
휴대폰번호로만 가입하고 있어서 따로 이메일은 중복확인하지 않았습니다. 인스타그램 가입절차를 살펴보니 두가지 방식 혼용되는데 저는 휴대폰번호로 가입하는 절차를 진행했습니다. 이메일로 바꾸는게 나을까요???

2021-12-18 03:31 UTC, evnif11 commented
## 수정 사항 간략한 한줄 요약
- 피드백 내용 반영

## 기타 질문 및 특이 사항
- 실제 인스타그램 가입절차 처럼 유저에게 이메일 가입 방식과 휴대폰으로 회원가입 받는 방식 둘 중에 하나를 선택할 수 있도록 하고 싶은데, 어떻게 구현해야할지 모르겠어서 먼저 휴대폰 방식을 먼저 적용하였습니다. 
- 타 사이트들의 회원가입 url을 살펴보니 google.com/signup , coupang.com/signup처럼 단순한 엔드포인트이더라구요. users/signup에서 users는 불필요한 거 같은데 최상단 url에 지정하면 모두 공통되게 적용될텐데 어떻게 처리하는게 좋을까요 ? 최상단에선 비워두고 하위 어플리케이션에서 필요한 곳에만 상세하게 url을 지정해주는 것도 괜찮을까요?

2021-12-18 07:16 UTC, Kang-kyunghun commented
1. 인스타처럼 구현하기 위해서는 당연히 email에 대한 처리, 핸드폰 번호에 대한 처리 모두가 있어야 합니다. 다음과 같은 절차가 필요할 것 같습니다.(큰 그림만 그려본 것이니 디테일한 부분은 한 번 생각해 보시면 좋을 것 같아요)
    - 프론트로부터 받은 값으로 가입된 회원이 있는지 판단(email, phone_number 모두 확인)
    - 프론트로부터 받은 값이 어떤 형식인지 판단 email인지 phone_number인지
    - 위의 판단을 바탕으로 회원가입 절차 진행
2.보통 이미 큰 서비스들은 Auth만 관리하는 서버를 따로 분리합니다. 그럴 경우 host/sigup 이렇게 올 수 있습니다.
저희가 구현하고 있는 사이트 구조상 users app에서 signup과 signin을 관리하고 있으니 불필요해 보인다고 생각하지는 않습니다.

2021-12-18 11:09 UTC, evnif11 commented
## 수정 사항 
- 이메일, 휴대폰 번호 둘 중 한가지 방식을 유저가 임의로 선택해 회원가입 가능하도록 모델 수정하였습니다.
- username필드가 unique하고 not null이기 때문에 이메일, 휴대폰 번호 둘 다 null=True 옵션을 주어도 괜찮다고 판단했습니다. 
- 데이터 이력관리를 위한 date 필드 추가했습니다.

2021-12-18 17:47 UTC, evnif11 commented
## 수정 사항
- try-except 구문 리팩토링

2021-12-20 05:14 UTC, evnif11 commented
피드백 주신 사항 반영했습니다!

2021-12-20 05:25 UTC, Kang-kyunghun commented
LGTM~~!!

2021-12-20 05:25 UTC, merged