[이민석] Mission 2: 모델링
wecode-bootcamp-korea/28-westagram-backend-3-team pull request #9
Opened 2021-12-18 04:56 UTC by leeminseok8

>wecode PR message template 및 체크 리스트 입니다. 
아래 사항들을 전부 작성/체크 하시고 PR 해주세요!

## 수정 사항 간략한 한줄 요약
(여기에 수정 사항에 대한 간략한 한줄 요약/제목 작성해 주세요.)
- 로그인 엔드포인트 구현(예시)
		 
## 수정 사항들 자세한 내용
(여기에 수정 사항에 대한 자세한 내용을 작성해 주세요.)
- 이메일 또는 핸드폰 번호로 로그인할 수 있음
- 실패시 에러 반환
- 성공시 200 OK 반환

## 기타 질문 및 특이 사항
(궁금한 사항들, 하면서 느낀 점들 공유해주실 것이 있으면 자유롭게 작성해 주세요.)
- 이메일 validation을 함수화할 수는 없나요? (예시) 

## 체크 리스트 (아래 사항들이 전부 체크되어야만 merge가 됩니다!)
조건을 만족한다면 각 빈칸에 x 표시 해주세요
- [ ] 필요한 test들을 완료하였고 기능이 제대로 실행되는지 확인 하였습니다.
- [ ] Wecode의 코드 스타일 가이드에 맞추어 코드를 작성 하였습니다.
- [ ] 제가 의도한 파일들과 수정 사항들만 커밋이 된 것을 확인 하였습니다.
- [ ] 본 수정 사항들을 팀원들과 사전에 상의하였고 팀원들 모두 해당 PR에 대하여 알고 있습니다.

2021-12-18 07:04 UTC, Kang-kyunghun requested changes

2021-12-18 07:04 UTC, Kang-kyunghun commented on students/minseok/westagram/users/models.py
> +    profile_photo   = models.ImageField()
```suggestion
    name          = models.CharField(max_length=50)
    email         = models.EmailField(max_length=128)
    password      = models.CharField(max_length=256)
    phone_number  = models.CharField(max_length=100)
    user_name     = models.CharField(max_length=50)
    website       = models.CharField(max_length=1000)
    introduce     = models.CharField(max_length=100)
    profile_imgae = models.CharField(mx_length=1000)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
```
1. 전화번호는 일반적으로 문자열로 간주 됩니다. 숫자 이외에도 '-'나 '+' 같은 기호가 들어갈 수 있습니다.
2. url 링크 주소 같은 경우 생각보다 긴 경우가 많아서 1000정도의 길이를 주면 좋을 것 같습니다.
3. photot보다는 image라는 단어를 더 많이 사용하고, 이미지 같은 경우 이미지를 직접 저장하는 것이 아닌, 이미지가 저장된 링크 주소를 저장하는 것이 일반적입니다.
4. 데이터의 이력 관리를 위해서 created_at, updated_at column을 추가해주세요.

```python
created_at = models.DateTimeField(auto_now_add=True)
updated_at = models.DateTimeField(auto_now=True)
```

2021-12-19 06:08 UTC, kyeongraekim requested changes
아래 내용 확인하여 수정해주세요!~

2021-12-19 06:08 UTC, kyeongraekim commented on students/minseok/westagram/users/models.py
> +# Create your models here.
불필요한 영문 주석은 삭제해주세요!~

2021-12-19 06:08 UTC, kyeongraekim commented on students/minseok/westagram/users/views.py
> +#         for user in users:
불필요한 view 파일이 같이 올라와있네요. 모델링에 해당되는 내용만 재푸시해주세요!~

2021-12-19 06:08 UTC, kyeongraekim commented on students/minseok/westagram/users/models.py
> +    email           = models.EmailField(max_length=128, null=True)
이메일 필드는 장고 form 속성을 적극적으로 활용 할 때 사용됩니다. 저희는 현재 최대한 pure한 장고 사용법을 익혀 기본 코드 원리를 먼저 깨우칠 수 있도록 안내해드리고 있습니다. 해당내용은 EmailField 가 아닌 CharField로 바꾸어 주세요!~

2021-12-19 06:08 UTC, kyeongraekim commented on students/minseok/westagram/users/models.py
> +    website         = models.CharField(max_length=1000, null=True)
website의 변수명의 기능적 네이밍이 다소 부족해보입니다. _url정도로 url이 들어감을 명시하는 것은 어떨까요?

2021-12-19 23:47 UTC, Kang-kyunghun commented
LGTM~!

2021-12-19 23:47 UTC, merged